#pragma once
#define EE_HANDS
#define VIAL_KEYBOARD_UID {0x95, 0x2d, 0x12, 0xd0, 0x54, 0xc9, 0x50, 0x48}
#define VIAL_TAP_DANCE_ENTRIES 8
#define VIAL_COMBO_ENTRIES 8
#define PICO_FLASH_SIZE_BYTES (1 * 1024 * 1024)
#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_RIGHT
#define POINTING_DEVICE_INVERT_X
#define POINTING_DEVICE_INVERT_Y
