#include QMK_KEYBOARD_H

#define DEFAULT_CPI 1500

void keyboard_post_init_user(void) {
    pointing_device_set_cpi(DEFAULT_CPI);
}

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(
        KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5,
        KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T,
        KC_GRAVE, KC_A, KC_S, KC_D, KC_F, KC_G,
        KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B,
        KC_RBRACKET, KC_LCTL, MO(3), KC_LGUI, KC_LALT, MO(1),
        KC_SPACE, QK_MACRO_0, KC_6, KC_7, KC_8, KC_9,
        KC_0, KC_MINUS, KC_Y, KC_U, KC_I, KC_O,
        KC_P, KC_QUOTE, KC_H, KC_J, KC_K, TD(0),
        TD(1), KC_ENTER, KC_NONUS_HASH, KC_N, KC_M, KC_COMMA,
        KC_DOT, KC_SLASH, KC_RO, KC_BSPC, KC_DEL, KC_LBRACKET,
        KC_EQUAL
    ),
    [1] = LAYOUT(
        KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5,
        KC_TRNS, KC_TRNS, KC_HOME, KC_UP, KC_END, KC_PGUP,
        KC_TRNS, KC_INSERT, KC_LEFT, KC_DOWN, KC_RIGHT, KC_PGDOWN,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, QK_MACRO_4, QK_MACRO_2,
        KC_VOLU, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_VOLD, KC_F6, KC_F7, KC_F8, KC_F9,
        KC_F10, KC_F11, KC_TRNS, KC_KP_7, KC_KP_8, KC_KP_9,
        KC_F12, KC_KP_ASTERISK, KC_TRNS, KC_KP_4, KC_KP_5, KC_KP_6,
        KC_KP_PLUS, KC_TRNS, KC_TRNS, KC_NUM, KC_KP_1, KC_KP_2,
        KC_KP_3, KC_KP_SLASH, KC_KP_MINUS, KC_KP_DOT, KC_KP_0, KC_TRNS,
        QK_BOOT
    ),
    [2] = LAYOUT(
        KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5,
        KC_TRNS, KC_TRNS, KC_HOME, KC_UP, KC_END, KC_PGUP,
        KC_TRNS, KC_TRNS, KC_LEFT, KC_DOWN, KC_RIGHT, KC_PGDOWN,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, QK_MACRO_3,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, QK_MACRO_1, KC_F6, KC_F7, KC_F8, KC_F9,
        KC_F10, KC_F11, KC_WH_U, KC_WH_D, KC_BTN3, KC_TRNS,
        KC_F12, KC_TRNS, KC_BTN4, KC_BTN1, KC_BTN2, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_WH_U, KC_WH_L, KC_WH_R,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_WH_D, KC_TRNS,
        KC_TRNS
    ),
    [3] = LAYOUT(
        KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5,
        LGUI(KC_TAB), KC_TRNS, KC_TRNS, LGUI(KC_UP), KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, LGUI(KC_LEFT), LGUI(KC_DOWN), LGUI(KC_RIGHT), KC_TRNS,
        KC_TRNS, KC_TRNS, KC_ACL0, KC_ACL1, KC_ACL2, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, QK_MACRO_1, KC_F6, KC_F7, KC_F8, KC_F9,
        KC_F10, KC_F11, KC_TRNS, LGUI(KC_D), LCG(KC_LEFT), SGUI(KC_RIGHT),
        KC_F12, KC_TRNS, KC_TRNS, LCG(KC_LEFT), LCG(KC_RIGHT), SGUI(KC_RIGHT),
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        QK_BOOT
    ),
};
