#pragma once

#define EE_HANDS
#define DYNAMIC_KEYMAP_LAYER_COUNT 5
#define PICO_FLASH_SIZE_BYTES (1 * 1024 * 1024)
#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_RIGHT
#define POINTING_DEVICE_INVERT_X
#define POINTING_DEVICE_INVERT_Y
#define PERMISSIVE_HOLD
